<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>JonsBlog2-4ef26ec3-8c28-4c51-8b26-e6556b4a53e7</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Blogs/" />
    </ItemGroup>

</Project>
